spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/twitter
    username: twitter
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:    
    show-sql: true
    hibernate:
      ddl-auto: update      
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    
