management:
  endpoints:
    web:
      exposure:
        include: "*"

#spring:
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/twitter
    username: twitteruser
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

